application: hostqueue-1146
version: 2
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css


- url: /groups
  script: _go_app

- url: /group_email
  script: _go_app

# Important! Even though there's a catch all routing above,
# without these two lines it's not going to work.
# Make sure you have this:
- url: /_ah/spi/.*
  script: _go_app