package hostqueue

import (
	
)

/* Sample curl to create an issue:
	curl --user "caspyin" -X POST --data 
	  '{"description":"Created via API","public":"true","files":{"file1.txt":{"content":"Demo"}}' 
	  https://api.github.com/gists
*/

const githubURI := "https://github.com/AnnAddicks/hostq/issues"

type Issue struct {
	Title string `json:"title"`
	Body string `json:"body"`
	Labels string `json:"labels"`
}

func (issue *Issue) new() {
	return &Issue{Labels:"AutoGenerated Error"}
}

func createGithubIssueAndPanic(err error) {



}